name: CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/mrsupiri/workflow
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t $IMAGE_NAME:commit-${GITHUB_SHA:0:8} .
      - run: docker tag $IMAGE_NAME $IMAGE_NAME:latest
      - run: docker push $IMAGE_NAME --all-tags
  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@master
      - name: Create a Release
        uses: go-semantic-release/action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          allow-initial-development-versions: false
          prepend: true
          changelog-file: CHANGELOG.md
      - name: Update CHANGELOG.md
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add CHANGELOG.md
          git commit -m "docs: Update the changelog"
          git push origin